version: v1.0
name: Production Deploy
blocks:
  - name: 'Deploy to Netlify'
    task:
      secrets:
        - name: netlify-authentication
      jobs:
        - name: Deploy Website
          commands:
            - nvm use 10
            - yarn global add netlify-cli
            - cache restore starter-build-$SEMAPHORE_GIT_BRANCH
            - netlify deploy --dir=sites/core/public --prod
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
